template v_4/api/urls.py
from django.urls import path
from .views import Main
from .views import Login
from .views import Logout
from .views import AuthCheck


app_name = 'api'
urlpatterns = [
    path('', Main.as_view(), name='main'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('auth_check/', AuthCheck.as_view(), name='auth_check')
]

template v_4/bot/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.getMessage),
]

template v_4/server/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("bot", include("bot.urls")),
    path('', include('api.urls')),
]

template v_4/api/models.py
from django.db import models
from django.utils import timezone

class TelegramUsers(models.Model):
    session_id = models.CharField(max_length=56, unique=True)
    tg_id = models.CharField(max_length=56, default="no-auth")
    name = models.CharField(max_length=56, default="no-auth")
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.tg_id
    class Meta:
        ordering = ['-created']

template v_4/bot/models.py
from dataclasses import dataclass, field
import requests, json
from server.const import TOKEN_TG

@dataclass
class Message:
    chat_id : str = None
    message_id : str = None
    username : str = None
    last_name : str = None
    first_name : str = None
    text : str = None
    photo : str = None
    voice : str = None
    video_note : str = None
    video : str = None
    document : str = None
    callback : str = None
    error : bool = field(init=False)

    def __post_init__(self):
        if not self.chat_id  or not self.message_id:
            self.error = True
        else:
            self.error = False

    def sendMessage(self, keyboard={}, text="text"):

        data = { 
            "chat_id": self.chat_id,
            "text": text,
            "reply_markup" : json.dumps(keyboard)
        }
        response = requests.post(f"https://api.telegram.org/bot{TOKEN_TG}/sendMessage", data)
        return response
    

    def editMessage(self, text=" ", message_id=None, keyboard={}):
        if not message_id:
            message_id = self.message_id

        data = { 
            "chat_id": self.chat_id,
            "text": text,
            "message_id" : message_id,
            "reply_markup" : json.dumps(keyboard)
        }
        response = requests.post(f"https://api.telegram.org/bot{TOKEN_TG}/editMessageText", data)
        return response

    def deleteMessage(self, message_id=None):
        if not message_id:
            message_id = self.message_id

        data = {
            "chat_id": self.chat_id,
            "message_id" : message_id
        }
        response = requests.post(f"https://api.telegram.org/bot{TOKEN_TG}/deleteMessage", data)
        return response
    
        
    def callbackJson(self):
        try:
            callback_json = json.loads(self.callback)  
        except:
            callback_json = None
        return callback_json

template v_4/api/views.py
from django.views import View
from django.shortcuts import render, redirect
from .models import TelegramUsers
from django.http import JsonResponse

from server.const import BOT_NAME
from server.const import HOST_DNS

class Main(View):
    def get(self, request):
        bot_name = BOT_NAME
        print(BOT_NAME)
        session_id = request.session["session_id"]
        auth = request.session["auth"]
        return render(request, 'main.html', {"bot_name":bot_name, "session_id":session_id, "auth":auth, "dns":HOST_DNS})
    
class Login(View):
    def get(self, request):
        session_id = request.session["session_id"]
        telegram_login_url = f"https://t.me/{BOT_NAME}?start={session_id}"
        return redirect(telegram_login_url)

class AuthCheck(View):
    def get(self, request):
        session_id = request.GET.get('session_id')
        if TelegramUsers.objects.filter(session_id=session_id).exists():
            return JsonResponse({'result': True})
        else:
            return JsonResponse({'result': False})

class Logout(View):
    def get(self, request):
        session_id = request.session["session_id"]
        if TelegramUsers.objects.filter(session_id=session_id).exists():
            user = TelegramUsers.objects.get(session_id=session_id)
            user.session_id = "None"
            user.save()

        request.session["session_id"]=None
        request.session["auth"]=None
        request.session["name"]=None
        request.session["org_select"]=None
        return redirect("/")

template v_4/bot/views.py
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import telegram_format
from api.models import TelegramUsers
from server.const import BACK_BUTTON
from server.const import CLEAN_BUTTON

@api_view(['POST'])
def getMessage(request):
    message = telegram_format(request.data)
    print(message)

    if message.text and "/start" in message.text and len(message.text) > 8:
        signin(message=message, request=request)
    return Response("ok", status=200)

def signin(message, request):
    tg_id = message.chat_id
    name = message.chat_id
    text=message.text
    session_id = text.replace("/start ", "")
    qr_check = False

    if "qrcode" in session_id:
        session_id = session_id.replace("qrcode", "")
        qr_check = True

    if message.first_name:
        name = message.first_name
    elif message.username:
        name = message.username


    if TelegramUsers.objects.filter(tg_id=tg_id).exists():
        user = TelegramUsers.objects.get(tg_id=tg_id)
        user.session_id = session_id
        user.save()

    elif not TelegramUsers.objects.filter(tg_id=tg_id).exists():
        user=TelegramUsers.objects.create(
            session_id=session_id,
            tg_id=tg_id,
            name=name
        )

    else:
        print("")
        print("no match session with BD")
        print("")
        return message.sendMessage(text="Что-то пошло не так, попробуйте авторизоваться еще раз!", keyboard=CLEAN_BUTTON)
    
    if qr_check:
        return message.sendMessage(text="Вход выполнен успешно!")
    else:
        return message.sendMessage(text="Вход выполнен успешно!", keyboard=BACK_BUTTON)

template v_4/api/templates/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}bitstock{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/svg+xml" href="{% static 'icon.png' %}">
{% tailwind_css %}
</head>
<body class="">
    {% if request.session.auth %}
    <div class="bg-amber-50 shadow-md flex pl-10 items-center justify-between">
        <div class="flex">
            <form action="{% url 'api:main' %}" method="GET">
                <button class="hover:bg-stone-300 h-10 w-40 items-center flex justify-center duration-500 text-lg">
                    <pre>{{request.session.name}}</pre>
                </button>
            </form>
        </div>

        <form action="{% url 'api:logout' %}" method="GET">
            <button class="hover:bg-stone-300 h-10 w-40 items-center flex justify-center duration-500 text-lg">
                <pre>logout</pre>
            </button>
        </form>
    </div>

    {% endif %}

    <div class="px-10 mt-32">
    {% block content %}{% endblock %}
    </div>


</body>
</html>

template v_4/api/templates/info.html
{% extends 'base.html' %}
{% block title %}
info
{% endblock %}
{% block content %}
{% load static %}

<div class="">
    <pre>{{info}}</pre>
</div>


{% endblock %}

template v_4/api/templates/main.html
{% extends 'base.html' %}
{% block title %}
main
{% endblock %}
{% block content %}

{% if request.session.auth != True %}
<div class="flex justify-center items-center h-screen">
  <div class="">
    <form class="" action="{% url 'api:login' %}" method="GET">
      <button class="text-lg shadow-md w-[256px] border-2 h-20 text-center rounded-3xl hover:bg-stone-300 bg-amber-50 border-stone-700 duration-500" type="submit">
        <pre>telegram login</pre>
      </button>
    </form>

    <div class="border-stone-700 shadow-md mt-10 pb-[20px] pl-[20px] pr-[20px] pt-[10px] border-2 rounded-3xl bg-amber-50" id="qr_box">
      <div class="pb-2 text-center text-lg ">
        <pre>qr code login</pre>
      </div>
      <div class="" id="qrcode"></div>
    </div>

    <form class="hidden pt-[10px]" id="refresh" action="{% url 'api:main' %}" method="GET">
      <button class="text-lg shadow-md w-[256px] duration-500 border-2 border-stone-700 hover:bg-stone-300 bg-amber-50 h-20 text-center rounded-3xl" type="submit">
        <pre>обновить qr code</pre>
      </button>
    </form>

  </div>
</div> 

<script src="https://cdn.jsdelivr.net/gh/davidshimjs/qrcodejs/qrcode.min.js"></script>

<script>
  var options = {
    text: "https://t.me/{{bot_name}}?start={{session_id}}qrcode",
    width: 216, // QR code width
    height: 216, // QR code height
    colorDark: "#1C1917", // Foreground color
    colorLight: "#FFFBEB" // Background color
  };
  new QRCode(document.getElementById("qrcode"), options);

  function pollCheckEndpoint(startTime) {
    if (!startTime) {
        startTime = Date.now();
    }

    const timeLimit = 20000;

    fetch('https://{{dns}}/auth_check/?session_id={{session_id}}')
        .then(response => response.json())
        .then(data => {
            console.log(data.result);
            // Check { "result": true } or { "result": false }
            if (data.result === true) {
                location.reload();
            } else {
                if (Date.now() - startTime < timeLimit) {
                    setTimeout(() => pollCheckEndpoint(startTime), 1000);
                } else {
                    console.log('Polling stopped: time limit reached.');
                    document.getElementById('qr_box').classList.add('hidden');
                    document.getElementById('refresh').classList.remove('hidden');
                }
            }
        })
        .catch(error => {
            console.error('Error fetching data:', error);
        });
}

if ("{{auth}}" != true) {
    pollCheckEndpoint();
}

</script>

{% endif %}
{% endblock %}

template v_4/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>